### ISSUE TITLE
adding project parameter

### ISSUE THREAD

**Issue by matteoredaelli** [sohlex/botkit-rasa#5]
The /parse get request can accept a "project" parameter (instead of the old model parameter)

$ curl 'localhost:5000/parse?q=hello&project=hotels'
$ curl -XPOST localhost:5000/parse -d '{"q":"I am looking for Chinese food", "model": "restaurants"}'

as you can see at https://github.com/RasaHQ/rasa_nlu/blob/master/docs/http.rst

is it possible to manage it in this package?

thanks
matteo

**Comment by sohlex** [comment]
I'll do it asap, seems trivial. Thanks for the heads up!

**Comment by sohlex** [comment]
Thank you for your PR (#6), sorry it took some time to merge it!
